// JavaScript Document
;(function(obj){
	obj.set({
		name:"about",
		par:"a/b/f/e/k",
		tem:["about"],
		fn:function(data){
			if(!app.cookies("user")){
				$("#leftButton").show();
			$("#leftButton").html("登录");
			$("#leftButton").unbind("tap").bind("tap",function(){
				window.location.hash="index";
				});
				}else{
					$("#leftButton").hide();
					}
			
			$("#centerTitle").html("关于我们");
			$("#rightButton").html("注册");
			$("#rightButton").unbind("tap").bind("tap",function(){
				window.location.hash="register";
				});
			$("#scroller").html(data.tem[0]);
			$("#scroller").find("[D_type='navPoint']").each(function(){
				$(this).unbind("tap").bind("tap",function(){
					window.location.hash=$(this).attr("D_data");
					})
				});
			myScroll.refresh();
			}
		})
	})(app.control);