// JavaScript Document
;(function(obj){
	obj.set({
		name:"account",
		par:"a/b/f/e/k",
		tem:["account"],
		fn:function(data){

					$("#leftButton").hide();
			$("#centerTitle").html("个人中心");
			$("#rightButton").html("返回");
			$("#rightButton").unbind("tap").bind("tap",function(){
				window.history.go(-1)
				});
			if(app.cookies("user")){
				$("#scroller").html(data.tem[0]);
			$("#scroller").find("[D_type='navPoint']").each(function(){
				$(this).unbind("tap").bind("tap",function(){
					window.location.hash=$(this).attr("D_data");
					})
				});
			myScroll.refresh();
				}else{
					alert("请先登录");
					window.location.hash="index";
					}
			}
		})
	})(app.control);